name: Ruby

on:
  push:
    branches:
      - "*"

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4

    - uses: browser-actions/setup-chrome@v1
      id: setup-chrome

    - name: Set env vars
      run: |
        echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run rubocop
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rspec
